mgrs/Web/Areas/Main/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Model;
using Utls;
using BLL;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Data;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using System.Net;
using System.Configuration;
using Web.Areas.Main.Models;
using Newtonsoft.Json;
using Web.Models;

namespace Web.Areas.Main.Controllers
{
    public class MatchController : BaseController
    {
        //
        // GET: /Main/Match/

        public ActionResult Index(string matchname, string area2, int? pageIndex)
        {
            var teams = new List<tblmatch>();
            try
            {
                teams = new MatchBll().GetMatchs(matchname, area2, pageIndex.GetValueOrDefault(1));
                List<SelectListItem> Status = new MemberBll().GetDict(4);
                ViewData["Status"] = Status;
            }
            catch (Exception e)
            {

            }
            return View(teams);
        }

        public ActionResult Create()
        {

            List<SelectListItem> Status = new MemberBll().GetDict(4);
            foreach (SelectListItem r in Status)
            {
                ViewBag.Status += "<option value='" + r.Value.ToString() + "'>" + r.Text.ToString() + "</option>";
            }
            List<SelectListItem> Ispic = new MemberBll().GetDict(10);
            foreach (SelectListItem r in Ispic)
            {
                ViewBag.Ispic += "<option value='" + r.Value.ToString() + "'>" + r.Text.ToString() + "</option>";
            }
            tblmatch model = new tblmatch();
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection fc)
        {
            var model = new tblmatch();
            model.Match_id = Guid.NewGuid().ToString();
            model.Match_name = fc["Match_name"].ToString();
            model.Content = fc["Content"].ToString();
            model.Notice = fc["Notice"].ToString();
            model.Area1 = fc["Area1"].ToString();
            model.Area2 = fc["Area2"].ToString();
            if (fc["Date1"] != "")
            {
                model.Date1 = DateTime.Parse(fc["Date1"].ToString());
            }
            if (fc["Date2"] != "")
            {
                model.Date2 = DateTime.Parse(fc["Date2"].ToString());
            }
            if (fc["Date3"] != "")
            {
                model.Date3 = DateTime.Parse(fc["Date3"].ToString());
            }
            if (fc["Date4"] != "")
            {
                model.Date4 = DateTime.Parse(fc["Date4"].ToString());
            }
            string filename = "";

            HttpFileCollectionBase files = Request.Files;
            HttpPostedFileBase file = files["Pic1"];
            if (file != null)
            {
                filename = file.FileName.Substring(file.FileName.LastIndexOf(".") + 1);
                if ((filename.ToUpper() == "PNG" || filename.ToUpper() == "JPG") && file.ContentLength / 1024 < 2000)
                {
                    string path = Server.MapPath("~/UploadFiles/");
                    filename = "Big_" + DateTime.Now.ToString("yyyyMMddHHmmss") + "." + filename;
                    file.SaveAs(path + filename);
                    model.Pic1 = filename;
                }
            }

            HttpPostedFileBase file2 = files["Pic2"];
            if (file2 != null)
            {
                string filename2 = file2.FileName.Substring(file2.FileName.LastIndexOf(".") + 1);
                if ((filename2.ToUpper() == "PNG" || filename2.ToUpper() == "JPG") && file2.ContentLength / 1024 < 2000)
                {
                    string path = Server.MapPath("~/UploadFiles/");
                    filename = "Small_" + DateTime.Now.ToString("yyyyMMddHHmmss") + "." + filename2;
                    file2.SaveAs(path + filename);
                    model.Pic2 = filename;
                }
            }

            HttpPostedFileBase Tasklogo = files["Tasklogo"];
            if (Tasklogo != null)
            {
                filename = Tasklogo.FileName.Substring(Tasklogo.FileName.LastIndexOf(".") + 1);
                if ((filename.ToUpper() == "PNG" || filename.ToUpper() == "JPG") && Tasklogo.ContentLength / 1024 < 2000)
                {
                    string path = Server.MapPath("~/UploadFiles/");
                    filename = "Tasklogo_" + DateTime.Now.ToString("yyyyMMddHHmmss") + "." + filename;
                    Tasklogo.SaveAs(path + filename);
                    model.Tasklogo = filename;
                }
            }

            HttpPostedFileBase Logopic = files["Logopic"];
            if (Logopic != null)
            {
                string filename2 = Logopic.FileName.Substring(Logopic.FileName.LastIndexOf(".") + 1);
                if ((filename2.ToUpper() == "PNG" || filename2.ToUpper() == "JPG") && Logopic.ContentLength / 1024 < 2000)
                {
                    string path = Server.MapPath("~/UploadFiles/");
                    filename = "Logopic_" + DateTime.Now.ToString("yyyyMMddHHmmss") + "." + filename2;
                    Logopic.SaveAs(path + filename);
                    model.Logopic = filename;
                }
            }

            //string[] otherPics = null;
            //if(Request.Files.Count > 2){
            //    otherPics = new string[Request.Files.Count - 2];
            //    for (int i = 0; i < Request.Files.Count - 2; i++)
            //    {
            //        HttpPostedFileBase otherpic = files[i + 2];
            //        if (otherpic != null)
            //        {
            //            string filename3 = otherpic.FileName.Substring(otherpic.FileName.LastIndexOf(".") + 1);
            //            if ((filename3.ToUpper() == "PNG" || filename3.ToUpper() == "JPG") && otherpic.ContentLength / 1024 < 2000)
            //            {
            //                string path = Server.MapPath("~/UploadFiles/");
            //                filename = "Other_" + i.ToString() + "_" + DateTime.Now.ToString("yyyyMMddHHmmss") + "." + filename3;
            //                otherpic.SaveAs(path + filename);
            //                otherPics[i] = filename;
            //            }
            //        }
            //    }
            //}


            model.Ispic = fc["optIspic"].ToString();
            model.Status = fc["optStatus"].ToString();

            var bll = new MatchBll();

            try
            {
                bll.AddMatch(model, null);
            }
            catch (ValidException ex)
            {
                this.ModelState.AddModelError(ex.Name, ex.Message);
                return View(model);
            }

            return this.RefreshParent();
        }

        public ActionResult Edit(string id)
        {
            var bll = new MatchBll();
            var model = bll.GetMatchById(id);
            // var otherPics = bll.GetOtherPics(id);
            //ViewData["otherPics"] = otherPics;
            List<SelectListItem> Status = new MemberBll().GetDict(4);
            foreach (SelectListItem r in Status)
            {
                if (model.Status.ToString() == r.Value)
                    ViewBag.Status += "<option value='" + r.Value.ToString() + "'selected>" + r.Text.ToString() + "</option>";
                else
                    ViewBag.Status += "<option value='" + r.Value.ToString() + "'>" + r.Text.ToString() + "</option>";
            }
            List<SelectListItem> Ispic = new MemberBll().GetDict(10);

            foreach (SelectListItem r in Ispic)
            {
                if (model.Ispic.ToString() == r.Value)
                    ViewBag.Ispic += "<option value='" + r.Value.ToString() + "'selected>" + r.Text.ToString() + "</option>";
                else
                    ViewBag.Ispic += "<option value='" + r.Value.ToString() + "'>" + r.Text.ToString() + "</option>";
            }

            if (model.Isfore == 1)
            {
                ViewBag.Isfore += "<option value='1' selected>分段支付</option>";
                ViewBag.Isfore += "<option value='2'>立即支付</option>";
            }
            else
            {
                ViewBag.Isfore += "<option value='1'>分段支付</option>";
                ViewBag.Isfore += "<option value='2' selected>立即支付</option>";
            }
            return View(model);
        }



        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(string id, FormCollection fc)
        {
            var bll = new MatchBll();
            var model = bll.GetMatchById(id);

            model.Match_name = fc["Match_name"].ToString();
            model.Content = fc["Content"].ToString();
            model.Notice = fc["Notice"].ToString();
            model.Area1 = fc["Area1"].ToString();
            model.Area2 = fc["Area2"].ToString();
            if (fc["Date1"] != "")
            {
                model.Date1 = DateTime.Parse(fc["Date1"].ToString());
            }
            if (fc["Date2"] != "")
            {
                model.Date2 = DateTime.Parse(fc["Date2"].ToString());
            }
            if (fc["Date3"] != "")
            {
                model.Date3 = DateTime.Parse(fc["Date3"].ToString());
            }
            if (fc["Date4"] != "")
            {
                model.Date4 = DateTime.Parse(fc["Date4"].ToString());
            }

            string filename = "";
            HttpFileCollectionBase files = Request.Files;
            HttpPostedFileBase file = files["Pic1"];
            if (file != null)
            {
                filename = file.FileName.Substring(file.FileName.LastIndexOf(".") + 1);
                if ((filename.ToUpper() == "PNG" || filename.ToUpper() == "JPG") && file.ContentLength / 1024 < 2000)
                {
                    string path = Server.MapPath("~/UploadFiles/");

mgrs/Web/Areas/Main/Views/Match/Coupon.cshtml
@using Utls;
@using Model;
@using Web;
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model PagedList<tblcouponView>

<div class="row-fluid">
    <div class="span2">
        <div>
            <a class="btn red" id="delete" href="javascript:;">
                    <i class="icon-trash icon-white">
                    </i>删除
            </a>
            <a class="btn blue thickbox" title='添加邀请码' href="@Url.Action("CreateCoupon")?TB_iframe=true&height=550&width=500">
                <i class="icon-plus icon-white"></i>新增
            </a>
        </div>
    </div>
    <div class="span10">
        @using (Html.BeginForm(null, null, null, FormMethod.Get, new { id = "search" }))
        {
            <div class="dataTables_filter">
                <label>
                    <button type="submit" class="btn">
                        搜索 <i class="icon-search"></i>
                    </button>
                    <button type="button" id="exportExcel" class="btn" onclick="export_Excel();">导出 <i class="icon-download"></i></button>
                </label>
                <label>
                    <span>状态：</span>
                    <select id="optStatus" name="optStatus" class="m-wrap small" style="width:180px">
                        <option value="">请选择状态</option>
                        @Html.Raw(ViewBag.optStatus)
                    </select>
                </label>
                <label>
                    <span>队伍状态：</span>
                    <select id="optTeamStatus" name="optTeamStatus" class="m-wrap small" style="width:180px">
                        <option value="">请选择状态</option>
                        @Html.Raw(ViewBag.TeamStatus)
                    </select>
                </label>
                <label>
                    <span>类型：</span>
                    <select id="optType" name="optType" class="m-wrap small" style="width:180px">
                        <option value="">请选择类型</option>
                        @Html.Raw(ViewBag.Type)
                    </select>
                </label>
                <label>
                    <span>邀请码：</span>
                    @Html.TextBox("couponchar", null, new { @class = "m-wrap small" })
                </label>
                <label>
                    <span>电话：</span>
                    @Html.TextBox("mobile", null, new { @class = "m-wrap small" })
                </label>
                <label>
                    <span>公司名称：</span>
                    @Html.TextBox("company", null, new { @class = "m-wrap small" })
                </label>
                <label>
                    <span>队伍名称：</span>
                    @Html.TextBox("teamname", null, new { @class = "m-wrap small" })
                </label>
                <label>
                    <span>赛事名称：</span>
                    @Html.TextBox("matchname", null, new { @class = "m-wrap small" })
                </label>
            </div>
        }
    </div>
</div>
@*
    <div class="alert">
        <button class="close" data-dismiss="alert"></button>
        <strong>用户权限相关：</strong>
        请编辑其所属角色的权限，用户的权限是其所有角色所拥有的权限汇总！
    </div>*@
@using (Html.BeginForm("DeleteCoupon", "Match", FormMethod.Post, new { id = "mainForm" }))
{
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th style="width: 8px;">
                        <input type="checkbox" id="checkall" class="group-checkable" />
                    </th>
                <th>
                    赛事名称
                </th>
                <th>
                    队伍名称
                </th>
                <th>
                    队员
                </th>
                <th>
                    单位
                </th>
                <th>
                    电话
                </th>
                <th>
                    邀请码
                </th>
                <th>
                    线路名称
                </th>
                <th>
                    使用时间
                </th>
                <th>
                    类型
                </th>
                <th>
                    状态
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <td>
                        @if (m.Status == "0")
                        {
                            <input type="checkbox" class="checkboxes" name='ids' value='@m.Couponid' />
                        }    
                    </td>
                    <td>
                        @m.Match_name
                    </td>
                    <td>
                        @m.Teamname
                    </td>
                    <td>
                        @m.Nickname
                    </td>
                    <td>
                        @m.Company
                    </td>
                    <td>
                        @m.Mobile
                    </td>
                    <td>
                        @m.Couponchar
                    </td>
                    <td>
                        @m.Lines_name
                    </td>
                    <td>
                        @if (m.Usedtime != null)
                        {
                            @m.Usedtime.Value.ToString("yyyy-MM-dd HH:mm:ss");
                        }
                    </td>
                    <td>
                        @foreach (var item in ViewData["TTTT"] as List<SelectListItem>)
                        {
                            if (item.Value == m.Type)
                            {
                                @item.Text
                            }
                        }
                    </td>
                    <td>
                        @foreach (var item in ViewData["Status"] as List<SelectListItem>)
                        {
                            if (item.Value == m.Status)
                            {
                                @item.Text
                            }
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>

<script type="text/javascript">
    function export_Excel() {
        var matchname = $("#matchname").val();
        var teamname = $("#teamname").val();
        var company = $("#company").val();
        var mobile = $("#mobile").val();
        var couponchar = $("#couponchar").val();
        var optType = $("#optType").find("option:selected").val();
        var optStatus = $("#optStatus").find("option:selected").val();

        $.ajax({
            type: "POST",
            url: encodeURI("/Match/ExpCoupon?matchname=" + matchname + "&teamname=" + teamname + "&company=" + company + "&mobile=" + mobile + "&couponchar=" + couponchar + "&optType=" + optType + "&optStatus=" + optStatus),
            data: {},
            dataType: "text",
            success: function (data) {
                if (data != "") {
                    window.open("http://mgrs.chengshidingxiang.com/data/" + data);
                } else {
                    alert("导出失败！");
                }
            }
        });
    }
</script>

mgrs/Web/Areas/Main/Views/Match/Index.cshtml
@using Utls;
@using Model;
@using Web;
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model PagedList<tblmatch>

<div class="row-fluid">
    <div class="span4">
        <div>
            @*<a class="btn red" id="delete" href="javascript:;">
                <i class="icon-trash icon-white">
                </i>删除
            </a>*@ 
            <a class="btn blue thickbox" title='添加新赛事' href="@Url.Action("Create")?TB_iframe=true&height=550&width=700">
                <i class="icon-plus icon-white"></i>新增
            </a>
        </div>
    </div>
    <div class="span8">
        @using (Html.BeginForm(null, null, null, FormMethod.Get, new { id = "search" }))
        {
            <div class="dataTables_filter">
                <label>
                    <button type="submit" class="btn">
                        搜索 <i class="icon-search"></i>
                    </button>
                </label>
                <label>
                    <span>赛事名称：</span>
                    @Html.TextBox("matchname", null, new { @class = "m-wrap small" })
                </label>
                <label>
                    <span>区县：</span>
                    @Html.TextBox("area2", null, new { @class = "m-wrap small" })
                </label>
            </div>
        }
    </div>
</div>
@*
    <div class="alert">
        <button class="close" data-dismiss="alert"></button>
        <strong>用户权限相关：</strong>
        请编辑其所属角色的权限，用户的权限是其所有角色所拥有的权限汇总！
    </div>*@
@using (Html.BeginForm("Delete", "Match", FormMethod.Post, new { id = "mainForm" }))
{
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                @*<th style="width: 8px;">
                    <input type="checkbox" id="checkall" class="group-checkable" />
                </th>*@
                <th>
                    赛事名称
                </th>
                <th>
                    赛事描述
                </th>
                <th>
                    省市
                </th>
                <th>
                    区县
                </th>
                <th>
                    报名开始
                </th>
                <th>
                    报名结束
                </th>
                <th>
                    开赛时间
                </th>
                <th>
                    支付时间
                </th>
                <th>
                    状态
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    @*<td>
                        <input type="checkbox" class="checkboxes" name='ids' value='@m.Match_id' />
                    </td>*@
                    <td>
                        @m.Match_name
                    </td>
                    <td>
                        <span class="Content" title="@m.Content">@m.Content</span>
                    </td>
                    <td>
                       @m.Area1
                    </td>
                    <td>
                       @m.Area2
                    </td>
                    <td>
                           @m.Date1
                    </td>
                    <td>
                            @m.Date2
                    </td>
                    <td>
                            @m.Date3
                    </td>
                    <td>
                            @m.Date4
                    </td>
                    <td>
                        @foreach (var item in ViewData["Status"] as List<SelectListItem>)
                        {
                            if (item.Value == m.Status)
                            {
                                @item.Text
                            }
                        }
                    </td>
                    <td>
                        <a class="btn mini purple thickbox" title='编辑赛事资料' href="@Url.Action("Edit", new { id = m.Match_id })?TB_iframe=true&height=520&width=700">
                            <i class="icon-edit"></i>编辑
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>
<script type="text/javascript" src="@Url.Content("~/scripts/js/selector/jquery-1.10.js")"></script>
<script>
    $(document).ready(function () {
        //限制字符个数
        $(".Content").each(function () {
            var maxwidth = 40;
            if ($(this).text().length > maxwidth) {
                $(this).text($(this).text().substring(0, maxwidth));
                $(this).html($(this).html() + '...');
            }
        });
    });
</script>

mgrs/Web/Areas/Main/Views/Match/lineType.cshtml
@using Utls;
@using Model;
@using Web;
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model PagedList<tbllineView>

<div class="row-fluid">
    <div class="span4">
        <div>
            <a class="btn red" id="delete" href="javascript:;">
                <i class="icon-trash icon-white">
                </i>删除
            </a> <a class="btn blue thickbox" title='添加新线路类型' href="@Url.Action("LineCreate")?TB_iframe=true&height=520&width=500">
                <i class="icon-plus icon-white"></i>新增
            </a>
        </div>
    </div>
    <div class="span8">
        @using (Html.BeginForm(null, null, null, FormMethod.Get, new { id = "search" }))
        {
            <div class="dataTables_filter">
                <label>
                    <button type="submit" class="btn">
                        搜索 <i class="icon-search"></i>
                    </button>
                </label>
                <label>
                    <span>线路名称：</span>
                    @Html.TextBox("name", null, new { @class = "m-wrap small" })
                </label>
                <label>
                    <span>赛事名称：</span>
                    @Html.TextBox("matchname", null, new { @class = "m-wrap small" })
                </label>
            </div>
        }
    </div>
</div>
@*
    <div class="alert">
        <button class="close" data-dismiss="alert"></button>
        <strong>用户权限相关：</strong>
        请编辑其所属角色的权限，用户的权限是其所有角色所拥有的权限汇总！
    </div>*@
@using (Html.BeginForm("LineDelete", "Match", FormMethod.Post, new { id = "mainForm" }))
{
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th style="width: 8px;">
                    <input type="checkbox" id="checkall" class="group-checkable" />
                </th>
                <th>
                    赛事名称
                </th>
                <th>
                    线路名称
                </th>
                <th>
                    简介
                </th>
                <th>
                    队伍人数
                </th>
                <th>
                    队伍上限
                </th>
                @*<th>
                        个人价格
                    </th>*@
                @*<th>
                        团队价格
                    </th>*@
                <th>
                    状态
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="checkboxes" name='ids' value='@m.Lineid' />
                    </td>
                    <td>
                        @m.Matchname
                    </td>
                    <td>
                        @m.Name
                    </td>
                    <td>
                        <span class="Content" title="@m.Content">@m.Content</span>
                    </td>
                    <td>
                        @m.Players
                    </td>
                    <td>
                        @m.Count
                    </td>
                    @*<td>
                            @m.personprice
                        </td>*@
                    @*<td>
                            @m.teamprice
                        </td>*@

                    <td>
                        @foreach (var item in ViewData["Status"] as List<SelectListItem>)
                        {
                            if (item.Value == m.Status.ToString())
                            {
                                @item.Text
                            }
                        }
                    </td>

                    <td>
                        <a class="btn mini purple thickbox" title='编辑赛事资料' href="@Url.Action("LineEdit", new { id = m.Lineid })?TB_iframe=true&height=520&width=500">
                            <i class="icon-edit"></i>编辑
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>
<script type="text/javascript" src="@Url.Content("~/scripts/js/selector/jquery-1.10.js")"></script>
<script>
    $(document).ready(function () {
        //限制字符个数
        $(".Content").each(function () {
            var maxwidth = 40;
            if ($(this).text().length > maxwidth) {
                $(this).text($(this).text().substring(0, maxwidth));
                $(this).html($(this).html() + '...');
            }
        });
    });
</script>

mgrs/Web/Areas/Main/Views/Match/pics.cshtml
@using Utls;
@using Model;
@using Web;
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model PagedList<tblmatchpicsView>

<div class="row-fluid">
    <div class="span4">
        <div>
            <a class="btn red" id="delete" href="javascript:;">
                    <i class="icon-trash icon-white">
                    </i>删除
                </a>
            <a class="btn blue thickbox" title='添加赛事图片' href="@Url.Action("CreatePic")?TB_iframe=true&height=550&width=600">
                <i class="icon-plus icon-white"></i>添加
            </a>
        </div>
    </div>
    <div class="span8">
        @using (Html.BeginForm(null, null, null, FormMethod.Get, new { id = "search" }))
        {
            <div class="dataTables_filter">
                <label>
                    <button type="submit" class="btn">
                        搜索 <i class="icon-search"></i>
                    </button>
                </label>
                <label>
                    <span>赛事名称：</span>
                    @Html.TextBox("matchname", null, new { @class = "m-wrap small" })
                </label>
            </div>
        }
    </div>
</div>
@*
    <div class="alert">
        <button class="close" data-dismiss="alert"></button>
        <strong>用户权限相关：</strong>
        请编辑其所属角色的权限，用户的权限是其所有角色所拥有的权限汇总！
    </div>*@
@using (Html.BeginForm("PicDel", "Match", FormMethod.Post, new { id = "mainForm" }))
{
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th style="width: 8px;">
                    <input type="checkbox" id="checkall" class="group-checkable" />
                </th>
                <th>
                    赛事名称
                </th>
                <th>
                    省市
                </th>
                <th>
                    区县
                </th>
                <th>
                    赛事图片
                </th>
                <th>
                   创建时间
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="checkboxes" name='ids' value='@m.id' />
                    </td>
                    <td>
                        @m.match_name
                    </td>
                    <td>
                        @m.area1
                    </td>
                    <td>
                        @m.area2
                    </td>
                    <td>
                        <div class="control-group">
                            <div class="controls">
                                <div id="Pic2_view">
                                    <a class="thickbox" title='查看大图' href="http://@HttpContext.Current.Request.Url.Host:@Request.Url.Port/UploadFiles/@m.picture">
                                        <img style="width:100px;height:60px" src="http://@HttpContext.Current.Request.Url.Host:@Request.Url.Port/UploadFiles/@m.picture" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>
                        @if (m.createtime != null)
                        {
                            @m.createtime.Value.ToString("yyyy-MM-dd  HH:mm:ss");
                        }
                    </td>                  
                </tr>
            }
        </tbody>
    </table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>